server:
    port: 9000

# 文件上传目录配置
file:
    upload-dir: files/

# 数据库连接配置
spring:
    datasource:
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/cave_adventure_forum?serverTimezone=UTC
            username: root
            password: 123456

    data:
        redis:
            host: localhost
            port: 6379
            database: 0
            timeout: 5000

    mail:
        host: smtp.163.com
        protocol: smtp
        default-encoding: UTF-8
        username: 15294798563@163.com
        password: OMYYDXPVXDXNEBUL
        port: 465
        test-connection: true
        properties:
            mail:
                smtp:
                    auth: true
                    socketFactory:
                        class: javax.net.ssl.SSLSocketFactory
                    starttls:
                        enable: true
                        required: true

# MyBatis Plus配置
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: false
    global-config:
        db-config:
            id-type: auto

# 日志配置
logging:
    level:
        root: info
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
