name: Close Issues on Specific Commit Messages  
  
on:  
  push:  
    branches:  
      - master  
  
jobs:  
  close-issue-based-on-commit:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  
  
      - name: Check commit message and close issues  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: |  
          COMMIT_MSG=$(git log -1 --pretty=%B)  
  
          # Define target commit messages and corresponding issue numbers  
          declare -A TARGET_MESSAGES  
          TARGET_MESSAGES["1.0101--项目规划_文档编写_需求文档编写--何泽中--2024/07/03"]=2
          TARGET_MESSAGES["1.0102--项目规划_文档编写_功能文档编写--何泽中--2024/07/03"]=3
          TARGET_MESSAGES["1.0201--项目规划_图片绘制_简易ui绘制--何泽中--2024/07/03"]=4
          TARGET_MESSAGES["1.0202--项目规划_图片绘制_UML绘制--何泽中--2024/07/04"]=5
          TARGET_MESSAGES["1.0301--项目规划_人员安排与项目规划--何泽中--2024-07-05"]=6
          TARGET_MESSAGES["2.0101--代码编写_数据库编写_表和触发器的创建--何泽中--2024/07/04-2024/07/05"]=7
          TARGET_MESSAGES["2.0201--代码编写_数据库编写_数据模拟与审核_数据模拟--何泽中--2024/07/07"]=8
          TARGET_MESSAGES["2.0202--代码编写_数据库编写_数据模拟与审核_数据库审核--何泽中、王顺康、刘航--2024/07/07"]=9
          TARGET_MESSAGES["2.1101--代码编写_前端代码编写_完成html与css的编写_登录、注册、修改密码、修改信息编写--王轲--2024/07/03-2024/07/05"]=10 
          TARGET_MESSAGES["2.1102--代码编写_前端代码编写_完成html与css的编写_主页面的编写--王轲--2024/07/03-2024/07/09"]=11
          TARGET_MESSAGES["2.1103--代码编写_前端代码编写_完成html与css的编写_帖子详细页面的编写--王轲--2024/07/03-2024/07/09"]=12
          TARGET_MESSAGES["2.1201--代码编写_前端代码编写_js的编写_使用静态数据完成运行逻辑的分析与js的编写--王轲--2024/07/03-2024/07/09"]=13
          TARGET_MESSAGES["2.1202--代码编写_前端代码编写_js的编写_使用后端接口修改前端js文件--王轲--2024/07/10"]=14
          TARGET_MESSAGES["2.2101--代码编写_后端代码编写_与前后端人员沟通，设计函数接口，编写接口文档--何泽中--2024/07/05"]=15
          TARGET_MESSAGES["2.2201--代码编写_后端代码编写_pojo类编写--王顺康--2024/07/05"]=16
          TARGET_MESSAGES["2.2401--代码编写_后端代码编写_mapper类编写_userMapper、commentMapper类编写--王顺康--2024/07/07"]=17
          TARGET_MESSAGES["2.2402--代码编写_后端代码编写_mapper类编写_postMapper类编写--刘航--2024/07/07"]=18
          TARGET_MESSAGES["2.2501--代码编写_后端代码编写_service类编写_userService、commentService类编写--王顺康--2024/07/07-2024-07-10"]=19
          TARGET_MESSAGES["2.2502--代码编写_后端代码编写_service类编写_postService类编写--刘航--2024/07/07-2024-07-10"]=20
          TARGET_MESSAGES["3.0000--测试可视化游戏运行情况与修改优化--何泽中、刘航、王轲、王顺康--2024/07/11"]=21
          TARGET_MESSAGES["4.1100--自动化代码格式规范检查、测试、打包_自动化代码格式检查、测试用例检查--何泽中"]=22
          TARGET_MESSAGES["4.2100--自动化代码格式规范检查、测试、打包_自动化打包--何泽中--2024/07/11"]=23
  
          # Iterate over the target messages and check if the commit message matches  
          for msg in "${!TARGET_MESSAGES[@]}"; do  
            if [ "$COMMIT_MSG" = "$msg" ]; then  
              ISSUE_NUMBER=${TARGET_MESSAGES[$msg]}  
              echo "Closing issue #$ISSUE_NUMBER because the commit message matches: $msg"  
              curl -X PATCH \  
                -H "Accept: application/vnd.github.v3+json" \  
                -H "Authorization: token $GITHUB_TOKEN" \  
                -d '{"state": "closed"}' \  
                https://api.github.com/repos/cave_forum/issues/$ISSUE_NUMBER  
              break # Stop the loop once a match is found  
            fi  
          done  
  
          # If no match is found, you can optionally print a message here  
          # ...
